name: notes
description: A sample project for reviewing purpose
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  auto_route: ^7.5.0
  get_it: ^7.6.0
  injectable: ^2.1.2
  oxidized: ^6.0.0
  freezed_annotation: ^2.2.0
  riverpod_annotation: ^2.1.1
  flutter_riverpod: ^2.3.6
  flex_color_scheme: ^7.1.2
  styled_widget: ^0.4.1
  easy_localization: ^3.0.2
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  cloud_firestore: ^4.8.2
  google_fonts: ^5.0.0
  flutter_login: ^4.1.1
  drop_down_list: ^0.0.5
  responsive_framework: ^1.0.0
  mockito: ^5.4.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^7.1.1
  build_runner: ^2.4.6
  flutter_lints: ^2.0.2
  freezed: ^2.3.5
  injectable_generator: ^2.1.6
  json_serializable: ^6.7.1
  mockito: ^5.4.2

flutter:
  uses-material-design: true